POST http://localhost:3000/signin HTTP/1.1


Content-Type: application/json

{
    "username":"ygorazambuja",
    "password":"123456",
    "confirmPassword":"123456",
    "email":"ygorazambuja2@gmail.com"
}

###

POST http://localhost:3000/login HTTP/1.1

Content-Type: application/json

{
    "username":"ygorazambuja",
    "password":"123456"
}
